import { Trans } from "react-i18next";
import "./excel.scss";
import "../styles/inputs.scss";
import ReportService from "../services/report.service.js";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import Spinner from "../shared/Spinner";
import API_URL from "../services/APIURL";

function ReportToExcel() {
  const [data, setData] = useState({});
  const [isLoading, setIsLoading] = useState(true);

  function getData() {
    ReportService.getDownloadLinks()
      .then((res) => {
        setData(res.data);
        setIsLoading(false);
      })
      .catch((err) => {
        toast.error(<Trans>There is a problem loading data</Trans>);
        setIsLoading(false);
      });
  }

  useEffect(() => {
    getData();
  }, []);

  return (
    <>
      {isLoading ? (
        <Spinner></Spinner>
      ) : (
        <div className="container excel-page">
          <h2 className="mb-4">
            <Trans>
              Export bulk data of facilities and all types of equipment to MS
              Excel files
            </Trans>
          </h2>
          <p>
            <Trans>
              Export bulk data to two MS Excel files separately; 1) for all data
              related to all facilities, 2) for all data related to all items
              (equipment). Once you click on any or both of them, one or two MS
              Excel files will be generated by the application and you can find
              them in the Download folder of your PC.
            </Trans>
          </p>
          <div className="mt-4">
            <a href={API_URL + data.facility} download>
              <Trans>Export Facilities</Trans>
            </a>
            <a href={API_URL + data.item} download>
              <Trans>Export Items</Trans>
            </a>
          </div>
        </div>
      )}
    </>
  );
}

export default ReportToExcel;
